version: "3.9"

services:
  web:
    build: .
    image: web
    container_name: web
    ports:
      - 8000:5000
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    volumes:
      - .:/code
    env_file: .env
    environment:
      - PYTHONPATH=/code/email
      - QUEUE_NAME_PREFIX=prod

  worker:
    build: .
    command: celery -A tasks worker --loglevel=INFO
    volumes:
      - .:/code
    env_file: .env
    environment:
      - PYTHONPATH=/code/email
      - QUEUE_NAME_PREFIX=prod
    depends_on:
      - web
